click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("1354705142793.png")

click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("MainwindcwOT.png")
click("1355918636063.png")